"""baseline schema

Revision ID: c44eb758e88d
Revises: 
Create Date: 2026-08-07 21:01:39.277426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c44eb758e88d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_registration_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_slug'), 'race', ['slug'], unique=True)
    op.create_table('registrant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'registered', 'waitlisted', 'transferred', 'refunded', 'dns', 'dq', name='registrantstatus'), nullable=False),
    sa.Column('bib_number', sa.Integer(), nullable=True),
    sa.Column('waiver_accepted', sa.Boolean(), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'bib_number', name='uq_registrant_race_bib')
    )
    op.create_index(op.f('ix_registrant_bib_number'), 'registrant', ['bib_number'], unique=False)
    op.create_index(op.f('ix_registrant_email'), 'registrant', ['email'], unique=False)
    op.create_index(op.f('ix_registrant_race_id'), 'registrant', ['race_id'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('registrant_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('finish_time_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['registrant_id'], ['registrant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'place', name='uq_result_race_place')
    )
    op.create_index(op.f('ix_result_race_id'), 'result', ['race_id'], unique=False)
    op.create_index(op.f('ix_result_registrant_id'), 'result', ['registrant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_registrant_id'), table_name='result')
    op.drop_index(op.f('ix_result_race_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_registrant_race_id'), table_name='registrant')
    op.drop_index(op.f('ix_registrant_email'), table_name='registrant')
    op.drop_index(op.f('ix_registrant_bib_number'), table_name='registrant')
    op.drop_table('registrant')
    op.drop_index(op.f('ix_race_slug'), table_name='race')
    op.drop_table('race')
    # ### end Alembic commands ###
